development:
  # Configure available database clients. (required)
  sessions:
    # Defines the default client. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: echo_development
      hosts:
        - localhost:27017
      username: root
      password: password
test:
  sessions:
    default:
      database: feed_foundrie_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0


production:
  sessions:
    default:
      database: fun10sy
      hosts:
        - ds053090.mongolab.com:53090
      username: dev
      password: dev123